# Generated by Django 4.2 on 2024-09-16 11:50

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
