# Generated by Django 4.2 on 2024-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_employee_home_phone_alter_employee_work_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.IntegerField(),
        ),
    ]
