# Generated by Django 4.2 on 2024-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_employee_home_phone_alter_employee_work_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
