# Generated by Django 4.2 on 2024-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_employee_cabinet_alter_employee_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Администратор системы', 'Администратор системы'), ('Системный администратор', 'Системный администратор'), ('Контент менеджер аппарата управления', 'Контент менеджер аппарата управления'), ('Редактор', 'Редактор'), ('Пользователь системы', 'Пользователь системы')], max_length=50, null=True),
        ),
    ]
